[package]
name = "libdocker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bollard = "0.16.1"
anyhow = "1.0"
futures-util = "0.3"
tar = "0.4.40"
flate2 = "1.0.28"
