name: Clippy

on:
  workflow_call:

permissions:
  contents: read

jobs:
  clippy:
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v4
      - name: Setup build environment
        uses: ./.github/actions/setup
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: earthly --ci +clippy
