name: Clippy

on:
  workflow_call:

permissions:
  contents: read

jobs:
  clippy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Setup build environment
        uses: ./.github/actions/setup
      - name: Build
        run: earthly --ci +clippy
