name: Master

on:
  push:
    branches:
      - master

concurrency:
  group: master-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  issues: read
  checks: write

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
  clippy:
    uses: ./.github/workflows/clippy.yaml
    secrets: inherit
