name: Pr

on: [pull_request]

concurrency:
  group: pr-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  issues: read
  checks: write

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
