name: Pr

on: [pull_request]

concurrency:
  group: pr-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  issues: read
  checks: write

env:
  EARTHLY_BUILDKIT_HOST: "tcp://192.168.0.103:8372"

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
  clippy:
    uses: ./.github/workflows/clippy.yaml
    secrets: inherit
